// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.Protocol {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCp7Cg5FQ3JlYXR1cmVTdGF0ZRIYChRF",
            "Q1JFQVRVUkVfU1RBVEVfSURMRRAAEhoKFkVDUkVBVFVSRV9TVEFURV9NT1ZJ",
            "TkcQARIZChVFQ1JFQVRVUkVfU1RBVEVfU0tJTEwQAhIYChRFQ1JFQVRVUkVf",
            "U1RBVEVfREVBRBADKs8BCghFTW92ZURpchISCg5FTU9WRV9ESVJfTk9ORRAA",
            "EhAKDEVNT1ZFX0RJUl9VUBABEhIKDkVNT1ZFX0RJUl9ET1dOEAISEgoORU1P",
            "VkVfRElSX0xFRlQQAxITCg9FTU9WRV9ESVJfUklHSFQQBBIVChFFTU9WRV9E",
            "SVJfVVBfTEVGVBAFEhYKEkVNT1ZFX0RJUl9VUF9SSUdIVBAGEhcKE0VNT1ZF",
            "X0RJUl9ET1dOX0xFRlQQBxIYChRFTU9WRV9ESVJfRE9XTl9SSUdIVBAIQhuq",
            "AhhHb29nbGUuUHJvdG9idWYuUHJvdG9jb2xiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Protobuf.Protocol.ECreatureState), typeof(global::Google.Protobuf.Protocol.EMoveDir), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ECreatureState {
    [pbr::OriginalName("ECREATURE_STATE_IDLE")] Idle = 0,
    [pbr::OriginalName("ECREATURE_STATE_MOVING")] Moving = 1,
    [pbr::OriginalName("ECREATURE_STATE_SKILL")] Skill = 2,
    [pbr::OriginalName("ECREATURE_STATE_DEAD")] Dead = 3,
  }

  public enum EMoveDir {
    [pbr::OriginalName("EMOVE_DIR_NONE")] None = 0,
    [pbr::OriginalName("EMOVE_DIR_UP")] Up = 1,
    [pbr::OriginalName("EMOVE_DIR_DOWN")] Down = 2,
    [pbr::OriginalName("EMOVE_DIR_LEFT")] Left = 3,
    [pbr::OriginalName("EMOVE_DIR_RIGHT")] Right = 4,
    [pbr::OriginalName("EMOVE_DIR_UP_LEFT")] UpLeft = 5,
    [pbr::OriginalName("EMOVE_DIR_UP_RIGHT")] UpRight = 6,
    [pbr::OriginalName("EMOVE_DIR_DOWN_LEFT")] DownLeft = 7,
    [pbr::OriginalName("EMOVE_DIR_DOWN_RIGHT")] DownRight = 8,
  }

  #endregion

}

#endregion Designer generated code
